---
- name: Configure FundMe Server
  hosts: all
  become: yes

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone FundMe repository
      git:
        repo: https://github.com/Nidhi0827/Fundme.git
        dest: /home/ubuntu/Fundme
        force: yes

    - name: Start application with Docker Compose
      shell: cd /home/ubuntu/Fundme && docker-compose up -d
      become_user: ubuntu